# RickChat configuration file
# Do not change this!
config-version: 1.0

# Configurable messages, set the message to "-1" to cancel or leave empty to send nothing (prefix, suffix).
messages:
  default:
    prefix: "&c[&fBot&c] &eRick&f: "
    suffix: ""
  respond:
    help: "This is the help message"
    rules: "This is the rules message"
    welcome-back: "This is the welcome back message"

# Configurable permisisons,
permissions:
  mute: "rick.mute"




