# RickChat configuration file by dev-stan
# You can find the configuration file for the latest versions here:
# https://github.com/dev-stan/RickChat/blob/master/src/dev/stan/plugin/resources/config.yml
# Do not chpluginange this!
config-version: 1.0

# Set this to false to disable all plugin features. If a "plugin is disabled" message shows up even though the option below is set to "true"
# Update to the latest version and check for compatibility with other plugins.
enable-plugin: true


# Special player is not an operator or admin, the bot will send special messages to the player.
special-player: "Notch"

# Configurable commands, make sure the names are compatible with other plugins (for example don't set main to: "essentials", "luckperms").
# Reload the server to see the changes.
commands:

# Main command used for other subcommands.
  main: "rick"
  help: "help"
  reload: "reload"
  mute: "mute"

# Configurable messages, set the message to "-1" to cancel or leave empty to send nothing (prefix, suffix). 
# Reload the server to see the changes.
messages:

  # Default messages, used the most.
  default:
    prefix:
      enabled: true
      message: "&c[&fBot&c] &eRick&f: "
      
    suffix:
      enabled: false
      message: "."
      
    base-command: "Use /mute to turn off Rick, check out /help for more info."
    color: "&7"
    
  # Response messages, used by the "bot".
  respond:
  
    # Auto message when someone asks for help in chat.
    help:
      enabled: true
      message: "This is the help message"
    
    # Auto message when someone asks about rules in chat.
    rules:
      enabled: true
      messages: "This is the rules message"
    
    # The messages below will be sent once a player joins the game.
    welcome-back:
      enabled: true
      messages: 
        - "message1"
        - "message2"
        - "message3"
        - "message4"
        - "message5"
      

# Configurable permisisons
# Reload the server to see the changes.
permissions:
  admin: "rick.admin"
  reload: "rick.reload"
  mute: "rick.mute"




